### ISSUE TITLE
Gem installation of despeck requires `rmagick` and should provide adequate instructions

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/despeck#12]
On a mac:

```sh
brew install imagemagick@6
echo 'export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"' >> ~/.bash_profile
export PKG_CONFIG_PATH=/usr/local/opt/imagemagick@6/lib/pkgconfig
gem install despeck # or gem install rmagick
```

**Comment by ronaldtse** [comment]
Running executable `despeck` gives the following errors:

```
WARN: Unresolved specs during Gem::Specification.reset:
      nokogiri (>= 0)
      ffi (~> 1.9)
WARN: Clearing out unresolved specs.
```

**Comment by ronaldtse** [comment]
Our gem doesn't require `nokogiri` or `ffi`.

RTesseract requires `nokogiri`. Nokogiri itself may require ffi?

**Comment by nattfodd** [comment]
@ronaldtse yes, `ffi` is a gem which allows to load dynamic compiled libraries. Since `Nokogiri` have it's own native C extension, it uses `ffi` to create a binding for Ruby.

**Comment by nattfodd** [comment]
> Running executable despeck gives the following errors:
> 
> WARN: Unresolved specs during Gem::Specification.reset:
>       nokogiri (>= 0)
>       ffi (~> 1.9)
> WARN: Clearing out unresolved specs.
> 

Is this error still actual? Any tips how can I reproduce it?

**Comment by ronaldtse** [comment]
If you uninstall nokogiri, ffi, and despeck, then reinstall despeck, you should see the message.

**Comment by nattfodd** [comment]
@ronaldtse unfortunately, I can not reproduce the `unresolved specs` error. What I've tried:

* Installed despeck via `gem install despeck` and then used `despeck ocr 1.jpg` - it works
* Installed despeck via Gemfile + `bundle install` - works as well

The only thing I've noticed, `despeck` requires `pry` while it shouldn't - I'll fix that in the next version.

**Comment by ronaldtse** [comment]
It's already described here: https://github.com/riboseinc/despeck/blob/master/OCR.md

Closing.
