### ISSUE TITLE
`despeck ocr` usage issue

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/despeck#13]
I just ran this in the `despeck` gem folder but received an error:
```
bin/despeck ocr -l chi_sim spec/fixtures/red_watermark.jpg
```

=>

```
gems/2.3.0/gems/rtesseract-2.2.0/lib/rtesseract.rb:187:in `convert': No such file or directory @ rb_sysopen - /var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/1521805124.661379908.txt (RTesseract::ConversionError)
	from gems/2.3.0/gems/rtesseract-2.2.0/lib/rtesseract.rb:199:in `to_s'
	from /Users/mulgogi/src/despeck/lib/despeck/ocr.rb:13:in `text'
	from /Users/mulgogi/src/despeck/lib/commands/ocr.rb:15:in `execute'
	from gems/2.3.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
	from gems/2.3.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from gems/2.3.0/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
	from gems/2.3.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
	from bin/despeck:7:in `<main>'

```

**Comment by nattfodd** [comment]
@ronaldtse this error means you don't have `chi_sim` language installed or tesseract can't find those language training data

**Comment by ronaldtse** [comment]
@nattfodd I uninstalled tesseract completely and re-installed it -- and it worked!

I think there's a bug in `despeck ocr`. If I first `despeck` an image, and then run `tesseract` manually, the output is excellent. If I just use `despeck ocr` on an image directly, it is severely affected by the watermark.

Question: is `despeck ocr` designed to first clean the image and then run ocr, or is it just to ocr?

**Comment by nattfodd** [comment]
> Question: is despeck ocr designed to first clean the image and then run ocr, or is it just to ocr?

It only takes an image and extracts text from it, so yes -It's just OCR

**Comment by nattfodd** [comment]
If we need a command to do both - despeck & ocr, propose you name for that operation, and I'll implement that :)

**Comment by ronaldtse** [comment]
Yeah it’d be great if we have a command that does both together! Can’t think of a name right now though, so it’s up to you. 

In any case, we should explain in the README how to chain them.

**Comment by nattfodd** [comment]
Hi @ronaldtse , I've added combining command `despeck despeck` 😄 Also, updated readme to show examples of usage.

**Comment by ronaldtse** [comment]
Haha, nice one. Thank you @nattfodd!
