### ISSUE TITLE
Need help in installing despeck

### ISSUE THREAD

**Issue by anieshvishnu** [riboseinc/despeck#17]
I'm new to ruby I'm trying to install 'despeck' I keep getting this error. I'm is provided. Even i tried to install 'rmagick' still i keep getting this error.How to find out the necessary library for it. I've installed 'ruby-vips' also still not working.

clamp ~> 1.2
pdf-reader ~> 2.1
prawn ~> 2.2
rtesseract ~> 2.2
ruby-vips ~> 2.0
bundler ~> 1.16
pry >= 0
rake ~> 10.0
rspec ~> 3.0
rubocop ~> 0.52
I've install the above library but not rmagick ~> 2

 Any solution.

![image](https://user-images.githubusercontent.com/24503245/49221738-fbb5b600-f3ff-11e8-9a52-24ca3200a810.png)

![image](https://user-images.githubusercontent.com/24503245/49221510-5bf82800-f3ff-11e8-957f-c36c3aff52e4.png)

**Comment by jayhuang75** [comment]
Im in the Mac have the same issues, here is how i resolve it.

`brew uninstall imagemagick`
`brew install imagemagick@6`
`export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"`
`brew link --force imagemagick@6`

**Comment by ronaldtse** [comment]
Thanks @anieshvishnu and @jayhuang75 for the report and pointers.

@nattfodd could you help update the documentation to indicate this? In any case, it is a bit strange that despeck doesn't work with ImageMagick 7. That would be something we should work on.

**Comment by ronaldtse** [comment]
Ping @barockok could you help with this, perhaps adding the steps mentioned in https://github.com/riboseinc/despeck/issues/17#issuecomment-473728245 into the FAQ? Thanks.

**Comment by ronaldtse** [comment]
@anieshvishnu just FYI that @jayhuang75 's comments works, it's been included in the README now (aa707a9).

Thanks @jayhuang75 !
