### ISSUE TITLE
when using '--accurate', show error: composite: images do not have same numbers of bands (Vips::Error)

### ISSUE THREAD

**Issue by aspenlin** [riboseinc/despeck#19]
I was trying to make change only to the part with watermark, but it gives this error even when I tried on the image provided in the example by the authors. 
I was wondering whether this is because despeck returns a gray scale image however the original image is RGB. So when you use --accurate it encounter error when combining images with different numbers of bands?

**Comment by ronaldtse** [comment]
Thanks @aspenlin for the report. @nattfodd do you have time to check this out?

**Comment by barockok** [comment]
~should be fixed by #26~ my bad, that fixes unrelated to this issue.

**Comment by ronaldtse** [comment]
@aspenlin the issue has been fixed in 0.4.2, so closing this. Please re-open if the issue persists. Thanks!
