### ISSUE TITLE
when using '--sensitivity', somehow the program recognizes it as '--add-contrast'

### ISSUE THREAD

**Issue by aspenlin** [riboseinc/despeck#20]
I was testing what '--add-contrast' would give me, but after I used this, '--sensitivity' seems to be somehow changed to '--add-contrast'. It was working fine before but now whenever I tried to use '--sensitivity' it is giving me the result '--add-contrast' would generate. Really strange. Tried to restart computer but it didn't help.

**Comment by ronaldtse** [comment]
Thanks @aspenlin for the report. @nattfodd do you have time to check this out?

**Comment by ronaldtse** [comment]
Ping @barockok is this fixed? Thanks.

**Comment by barockok** [comment]
Yes, it is fixed.

here some samples :

## without options
```
despeck remove  spec/fixtures/red_watermark.jpg red_watermark_noptions.jpg
```
![red_watermark__normal](https://user-images.githubusercontent.com/474500/93229576-f1b1a280-f7a0-11ea-851c-2ab7ffc273f5.jpg)
## with --add-contrast
```
despeck remove --add-contrast  spec/fixtures/red_watermark.jpg red_watermark__add_contrast.jpg
```

![red_watermark__add_contrast](https://user-images.githubusercontent.com/474500/93229607-fa09dd80-f7a0-11ea-9ae1-cfff0c7b04c5.jpg)
## with --sensitivity 180 
```
despeck remove --sensitivity 180 spec/fixtures/red_watermark.jpg red_watermark__sensitivity_180.jpg
```
![red_watermark__sensitivity_180](https://user-images.githubusercontent.com/474500/93229670-08f09000-f7a1-11ea-9493-321eb2d3f6f7.jpg)
## with --sensitivity 130
```
despeck remove --sensitivity 130 spec/fixtures/red_watermark.jpg red_watermark__sensitivity_130.jpg
```
![red_watermark__sensitivity_130](https://user-images.githubusercontent.com/474500/93230731-312cbe80-f7a2-11ea-8625-677e2a9958b5.jpg)

**Comment by ronaldtse** [comment]
Thanks @barockok ! Closing.
